### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by meblum** [danishprakash/gosortstructs#3]
The [README.md](https://github.com/danishprakash/gosortstructs?tab=readme-ov-file#license) states that the project is under a MIT license, but the [LICENSE](https://github.com/danishprakash/gosortstructs/blob/main/LICENSE) file contains the GNU license.

**Comment by meblum** [comment]
I see that the referenced [vim plugin](https://github.com/danishprakash/vim-gosortstructs) also states MIT in the readme. Guess it's safe to assume that the intended license was indeed MIT?

**Comment by danishprakash** [comment]
You're right, I missed this somehow, fixed now.
